### PR TITLE
User Profile Customization

### PR DESCRIPTION
**Pull request by jyori1**
Imported material UI
Updating user credential functionality between mongodb/firebase working
Users can update any of their credentials and click update

Will work on the actual user profile later, also planning on moving the change password component to be under the customization component.
Screenshot 2024-11-27 at 9 20 11 PM
Changing bio
Screenshot 2024-11-27 at 9 20 24 PM
Screenshot 2024-11-27 at 9 20 58 PM

### CODE REVIEW

**Comment by cd721** [comment]
Not sure if this is just me but I am getting this error. I think we need to limit  image size.
image

**Comment by jyori1** [comment]
Fixed it, should compress the image prior to uploading and if it still exceeds 2MB limit, a pop up error will throw.

**Comment by cd721** [comment]
Honestly, I'm still having issues with the photo upload. I can't upload a pic that is  48 KB.

**Comment by jyori1** [comment]
What's the error output? I'm able to upload a pfp as large as 1.9 MB, is mongo community on?

**Comment by cd721** [comment]
Oh wait it is saying it can't find  my user ID

**Comment by jyori1** [comment]
Wait, what id is being printed out? Is it the same id populated in ur local DB?

Jo-Anne Rivera
Stevens Institute of Technology — Class of 2025
B.S. in Computer Science | Minor in Data Visualization
***@***.***

________________________________

**Comment by cd721** [comment]
I got it. Also I love your signature in the PR comment loool

**Comment by jyori1** [comment]
O thank goodness and lool i blame replying via email 😭

**Comment by cd721** [comment]
i'm mergin cause we need to get movin

**Pull request merged**
